version: '3.1'

services:

  master:
    image: vfarcic/jenkins
    ports:
      - 50000:50000
    environment:
      - JENKINS_OPTS="--prefix=/jenkins"
    networks:
      - proxy
      - default
    deploy:
      labels:
        - com.df.notify=true
        - com.df.distribute=true
        - com.df.servicePath=/jenkins
        - com.df.port=8080
    extra_hosts:
      - "${SLACK_HOST:-devops20.slack.com}:${SLACK_IP:-54.192.78.227}"
    secrets:
      - jenkins-user
      - jenkins-pass

  agent:
    image: vfarcic/jenkins-swarm-agent
    environment:
      - USER_NAME_SECRET=/run/secrets/${JENKINS_USER_SECRET:-jenkins-user}
      - PASSWORD_SECRET=/run/secrets/${JENKINS_PASS_SECRET:-jenkins-pass}
      - COMMAND_OPTIONS=-master http://master:8080/jenkins -labels 'prod' -executors 4
    networks:
      - default
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    secrets:
      - jenkins-user
      - jenkins-pass
    deploy:
      placement:
        constraints: [node.role == manager]

networks:
  proxy:
    external: true
  default:
    external: false

secrets:
  jenkins-user:
    external: true
  jenkins-pass:
    external: true